### ISSUE TITLE
Clean up error output

### ISSUE THREAD

**Issue by ghickman** [ghickman/linode#1]
Show the method being called on the API that fell over.

Print is probably not the nicest thing to do -> look at sys.error type stuff to clear that up.

**Comment by bsdlp** [comment]
this issue is kinda still relevant kinda?

```
>>> for domain in linode.domain.list.lol():
...     print(domain)
...
[domain.list.lol] The requested class does not existTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jchen/git/linode/linode/linode/api.py", line 27, in __call__
    return self.klass._worker_func(self.path, *args, **kwargs)
  File "/Users/jchen/git/linode/linode/linode/api.py", line 76, in _worker_func
    return self._request(api_kwargs)
  File "/Users/jchen/git/linode/linode/linode/api.py", line 69, in _request
    raise LinodeException(content.get('ACTION'), content.get('ERRORARRAY'))
linode.api.LinodeException: ('domain.list.lol', [{'ERRORCODE': 3, 'ERRORMESSAGE': 'The requested class does not exist'}])
```

It may be a good idea to print a newline between the error message and the beginning of the trace?

**Comment by ghickman** [comment]
Kind of yes. We should probably use logging for this too.
