### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by bsdlp** [ghickman/linode#3]
```
>>> for domain in linode.domain.list():
...     print(domain)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jchen/.venvs/dns3/lib/python3.4/site-packages/linode/api.py", line 25, in __call__
    return self.klass._worker_func(self.path, *args, **kwargs)
  File "/Users/jchen/.venvs/dns3/lib/python3.4/site-packages/linode/api.py", line 70, in _worker_func
    return self._request(api_kwargs)
  File "/Users/jchen/.venvs/dns3/lib/python3.4/site-packages/linode/api.py", line 61, in _request
    content = json.loads(r.content)
  File "/usr/local/Cellar/python3/3.4.0_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by bsdlp** [comment]
this particular trace can probably be fixed by decoding the bytestring before handing off to json.loads(). Working on a patch.

**Comment by ghickman** [comment]
Awesome, thanks for looking into this @fly!

**Comment by ghickman** [comment]
Oops, hadn't meant to close this one - sorry about that!

**Comment by bsdlp** [comment]
Oh, the PR that was merged should have done the needful to get py3 working

**Comment by ghickman** [comment]
Oh yes sorry about that.
